module.exports = {
    es: {
        translation: {
            
          BIENVENIDA_MSG: 'Bienvenido a Experis Formación. Para empezar, debes registrarte como usuario. Para esto, puedes decir: registro o quiero registrarme. <break time="1s"/>Si ya estás registrado, puedes decir: iniciar sesión',
          BIENVENIDO_USUARIO_MSG: '¡Hola %s! me alegra oirte de nuevo. <amazon:effect name="whispered">Si no eres %s di: cambiar de usuario.</amazon:effect>',
          BIENVENIDA_REGISTRO_HABILIDADES: '<break time="2s"/>todavía no has registrado tus habilidades técnicas. Esto es necesario para poder ofrecerte cursos y planes formativos. Para añadir tus habilidades puedes decir: registrar habilidades; o simplemente: habilidades',
          BIENVENIDA_REGISTRO_INTERESES: '<break time="2s"/>aún no tienes registrado ningún interés técnico o profesional. Sin esto, no podré recomendarte cursos y planes formativos de tu interés. Para nuevos intereses puedes decir: registrar intereses; o simplemente: intereses',  
          BIENVENIDA_REGISTRO_IDIOMAS: '<break time="2s"/>parece que aún no has registrado ningún idioma a tu perfil. Conocer los idiomas que manejas me permitiría recomendarte cursos en otros idiomas y cursos para reforzar tus idiomas según tu nivel. Para añadir idiomas puedes decir: registrar idiomas; o simplemente: idiomas',
          USUARIO_REGISTRADO_MSG: '<amazon:emotion name="excited" intensity="high">¡Perfecto, %s! Ya estás registrado en Experis Formación.</amazon:emotion>',
          OPCIONES_DISPONIBLES_MSG: 'en este punto, otras opciones disponibles son: ',
          OPCIONES_DISPONIBLES_AYUDA_MSG: 'Estas son las opciones que tengo para ti: ',
          OPCION_IDIOMAS_MSG: 'si deseas añadir idiomas a tu perfil, puedes decir: registrar idiomas, o idiomas.',
          OPCION_HABILIDADES_MSG: 'para registrar habilidades a tu perfil técnico, di: registrar habilidades, o habilidades',
          OPCION_INTERESES_MSG: 'si quieres agregar intereses profesionales a tu perfil, di: registrar intereses, o intereses',
          OPCION_SUGERENCIA_FORMACION_MSG: 'si deseas recibir sugerencias de cursos di: ¿qué cursos tienes para mí?. Para sugerencias de planes formativos dí: ¿qué planes formativos tienes para mí?',
          OPCION_FORMACIONES_USUARIO_MSG: 'para conocer tus cursos o planes formativos puedes decir: que tengo para, y después el día o la fecha. Si quieres consultar un rango de fechas puedes decir: que tengo entre, y despues los días o las fechas de la consulta. Por ejemplo, <amazon:emotion name="excited" intensity="high">¿qué tengo entre el lunes y el viernes?</amazon:emotion>',
          OPCION_REGISTRAR_USUARIO_MSG: 'para registrar un nuevo usuario di: quiero registrarme',
          OPCION_CAMBIAR_USUARIO_MSG: 'si quires cambiar de usuario puedes decir: cambiar de usuario',
          OPCION_SALIR_MSG: 'para salir di: salir, o adiós',
          OPCION_AYUDA_MSG: 'si quieres conocer todas las opciones disponibles puedes decir: ¡ayuda!',
          REGISTRAR_OTRO_IDIOMA_MSG: 'Si deseas añadir otro idioma, puedes decir: otro idioma',
          REGISTRAR_OTRA_HABILIDAD_MSG: 'Si quieres agregar otra habilidad, di: otra habilidad',
          REGISTRAR_OTRO_INTERES_MSG: 'para registar otro interés puedes decir: otro interés',
          ERROR_LLAMANDO_API_MSG: '<amazon:emotion name="disappointed" intensity="high">Ha ocurrido un error. %s</amazon:emotion>',
          HABILIDAD_REGISTRADA_EXITOSAMENTE_MSG: '<amazon:emotion name="excited" intensity="medium">¡habilidad registrada!</amazon:emotion>',
          INTERES_REGISTRADO_EXITOSAMENTE_MSG: '<amazon:emotion name="excited" intensity="medium">¡interés registrado!</amazon:emotion>',
          NO_HAY_SUGERENCIA_PLANES: '<amazon:emotion name="disappointed" intensity="high">No tenemos ningún Plan formativo que ofrecerte hoy. %s</amazon:emotion>',
          NO_HAY_SUGERENCIA_CURSOS: '<amazon:emotion name="disappointed" intensity="high">No tenemos ningún Curso que ofrecerte hoy. %s</amazon:emotion>',
          SUGERENCIA_CURSO: 'Hoy te puedo sugerir este curso: %s, empieza el día %s y acaba el día %s, ',
          SUGERENCIA_PLAN: 'Hoy te puedo sugerir este plan formativo: %s, empieza el día %s y acaba el día %s, ',
          APUNTARSE_O_SIGUIENTE: 'si quieres apuntarte dí Apúntame, si quieres otro di siguiente formación ',
          BUSCA_PRIMERO_FORMACION: 'Busca primero curso o plan formativo para apuntarte',
          REGISTRADO_FORMACION_CURSO: '<amazon:emotion name="excited" intensity="high">Has sido inscrito en el curso %s</amazon:emotion>',
          REGISTRADO_FORMACION_PLAN: '<amazon:emotion name="excited" intensity="high">Has sido inscrito en el plan formativo %s</amazon:emotion>',
          NO_HAY_FORMACIONES_MSG: 'No tienes formaciones para la fecha solicitada',
          NO_HAY_MAS_FORMACIONES_MSG: 'Ya no tienes más formaciones para la fecha solicitada',
          DIA_FORMACION_MSG: 'Para el día %s',
          RANGO_FORMACION_MSG: 'entre los días %s y %s',
          FORMACION_DESCRIPCION_MSG: ' tienes el %s %s.',
          CURSOS_PLAN_FORMATIVO_MSG: '<break time="1s"/>este plan formativo contiene los cursos: %s',
          CURSO_PRESENCIAL_ONLINE_MSG: '<break time="1s"/>este curso es %s.',
          CURSO_HORA_INICIO_MSG: '<break time="1s"/>Empieza a las %s ',
          CURSO_DURACION_MSG: ' y tiene una duración de %s horas.',
          CURSO_LUGAR_MSG: '<break time="1s"/>Puedes asistir a este curso en %s ',
          MAS_FORMACIONES_MSG: '<break time="2s"/>aún te %s por consultar. Si quieres continuar dí: siguiente',
          CAMBIAR_USUARIO_MSG: 'Si ya estás registrado puedes decir: iniciar sesión como, y tu nombre. Si aún no estás registrado dí: quiero registrarme', 
          ADIOS_MSG: '<amazon:emotion name="disappointed" intensity="high">¡Hasta luego %s!</amazon:emotion><break time="1s"/><amazon:emotion name="excited" intensity="high"> que vaya bien</amazon:emotion>',
          REFLECTOR_MSG: '',
          FALLBACK_MSG: 'Lo siento, no se nada sobre eso. Por favor inténtalo otra vez.',
          ERROR_MSG: 'Lo siento, ha habido un problema. Por favor inténtalo otra vez.'
        }
    },
    en: {
        translation: {
          WELCOME_MSG:  'Bienvenido a Experis Formación. Para empezar, debes registrarte como usuario',
          USUARIO_REGISTRADO_MSG: 'Perfecto! Ya estás registrado en Experis Formación',
          REGISTRAR_IDIOMAS_MSG: '¿Deseas añadir algún idioma a tu perfil profesional?',
          NO_IDIOMAS_MSG: 'Vale. Cuando desees añadir un nuevo idioma sólo tienes que decir: añadir idioma',
          HELP_MSG: '',
          GOODBYE_MSG: 'Hasta luego!',
          REFLECTOR_MSG: 'Acabas de activar %s',
          FALLBACK_MSG: 'Lo siento, no se nada sobre eso. Por favor inténtalo otra vez.',
          ERROR_MSG: 'Lo siento, ha habido un problema. Por favor inténtalo otra vez.'
        }
    }
}
